/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WacTgJv {
    }
}
declare global {
    interface HTMLWacTgJvElement extends Components.WacTgJv, HTMLStencilElement {
    }
    var HTMLWacTgJvElement: {
        prototype: HTMLWacTgJvElement;
        new (): HTMLWacTgJvElement;
    };
    interface HTMLElementTagNameMap {
        "wac-tg-jv": HTMLWacTgJvElement;
    }
}
declare namespace LocalJSX {
    interface WacTgJv {
    }
    interface IntrinsicElements {
        "wac-tg-jv": WacTgJv;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wac-tg-jv": LocalJSX.WacTgJv & JSXBase.HTMLAttributes<HTMLWacTgJvElement>;
        }
    }
}
